meta_product_name: "lestoitures.fr"
meta_title: "lestoitures.fr - Le portail de référence de la toiture : annuaire des professionnels, guides, articles, bons plans"
meta_description: "lestoitures.fr est un site internet spécialisé dans le référencement des professionnels de la toiture combinant présentation des entreprises, projets, articles ..."
meta_image: "lancieux_1200_630.jpg"                           # Une image dans votre dossier app/assets/images/
facebook_id: 1610742872283439
twitter_account: "@LesToitures"              # indispensable pour les Twitter Cards
